### ISSUE TITLE
[Tracking issue]: some next steps

### ISSUE THREAD

**Issue by jtoar** [redwoodjs/github-bot#72]
- [ ] clarify use of `Promise.all` vs `Promise.allSettled`
- [ ] https://github.com/redwoodjs/github-bot/issues/71
- [ ] https://github.com/redwoodjs/github-bot/issues/70
- [ ] https://github.com/redwoodjs/github-bot/issues/66
